(begin
    (define (odd x)  
      (cond ((= x 0) 0)
            ((= x 1) 1)
            (else (even (- x 1)))))
    (define (even x)  
      (cond ((= x 0) 1)
            ((= x 1) 0)
            (else (odd (- x 1)))))
    (display (even 1000000))
    (newline)
    (display (odd  1000000))
)
